nav:
  - Home: 'index.md'
  - OSes and hardware:
      - macOS: 'os/macos/index.md'
      - Linux: 'os/linux/index.md'
      - All: 'os/general/index.md'
  - General:
      - The lab: 'general/the_lab.md'
      - Internship and new members: 'internship/index.md'
      - Work method: 'general/work_method.md'
      - Apps: 'apps/index.md'
      - Technological services: 'general/technological_services.md'
      - External services: 'general/external_services.md'


site_name: SAMI ETS Lab Documentation
repo_url: https://github.com/sami-ets/Documentation

markdown_extensions:
  - admonition
  - smarty
  - sane_lists

theme: readthedocs