pages:
  - Home: 'index.md'
  - Getting Started: 'getting_started.md'
  - Configuration: 'configuration.md'

site_name: SAMI ETS Lab Documentation
repo_url: https://github.com/sami-ets/Documentation

markdown_extensions:
  - admonition
  - smarty
  - sane_lists

theme: readthedocs